CREATE TABLE IF NOT EXISTS conversations (
  id BIGSERIAL PRIMARY KEY,
  chatwoot_conversation_id TEXT NOT NULL UNIQUE,
  contact_id TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'AI' CHECK (mode = 'AI'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
